language: python
sudo: enabled
python:
  - 3.6
  - 3.7.1

before_install:
  - echo 'start'
  - sudo apt-get update
  - sudo apt-get install -y python3-dev python3-pip

install:
  - pip install -r requirements.txt

script:
  - python3 bot.py